[package]
name = "rgrep"
version = "0.1.0"
authors = ["nestyy"]
edition = "2021"
rust-version = "1.80"

[dependencies]
anyhow = "1.0.68"
bytes = "1.3.0"
clap = { version = "4.5.31", features = ["derive"] }
thiserror = "1.0.38"
